version: '3.8'

services:
  opensearch-node1:
    image: opensearchproject/opensearch:2.9.0
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m

      - plugins.security.ssl.http.enabled=false
      - plugins.security.allow_default_init_securityindex=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin

    ulimits:
      memlock:
        soft: -1
        hard: -1

    ports:
      - "9200:9200"
      - "9600:9600"

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.9.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=http://opensearch-node1:9200
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=admin
    depends_on:
      - opensearch-node1

  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:7.16.3
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/data:/usr/share/logstash/data
    ports:
      - "5044:5044"
    depends_on:
      - opensearch-node1

volumes:
  opensearch-data:
